version: '3.5'
services:
  mongo:
    image: mongo
    command: --smallfiles
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - database

networks:
  default:
    name: hnetwork